### ISSUE TITLE
bug: first  drawing state is incorrect 

### ISSUE THREAD

**Issue by reslear** [tmg0/hero-motion#108]
I know about https://github.com/tmg0/hero-motion/issues/100#issuecomment-2194035260, but I still need to open an issue so others know. 

repro: Demo StackBlitz

video:

https://github.com/tmg0/hero-motion/assets/12596485/d4e97303-17b3-44ff-8deb-f32189187378

slowed 1 clik - ❌ bug:

https://github.com/tmg0/hero-motion/assets/12596485/0aea9e8e-9105-4eb7-9eb0-76802e76a37f

slowed 2 click - ✅ good:

https://github.com/tmg0/hero-motion/assets/12596485/7776077b-c483-4279-bd1d-4fbcf2157901

**Comment by tmg0** [comment]
Thank you very much for your input on improving `hero-motion`. Apologizing for focusing on the positioning issue in #100  and overlooking this one.

This issue has been fixed in version `v0.2.5`. Please try update dependencies to resolve this problem.

**Comment by reslear** [comment]
I tested it, everything works fine, thanks for the quick fix, powerful 🚀
