### ISSUE TITLE
laggy

### ISSUE THREAD

**Issue by reslear** [tmg0/hero-motion#96]
https://github.com/tmg0/hero-motion/assets/12596485/2de46a91-70bf-452e-bbfd-fa3bd6f9ca7a

Repro: 
Go to https://stackblitz.com/~/github.com/tmg0/hero-motion and run `play:vite`

**Comment by tmg0** [comment]
Thank you for using this package!

It seems that there is an issue with the transition animation of `hero-motion` when previewing in Stackblitz, and I am trying to resolve it.

**Comment by tmg0** [comment]
This issue has been fixed in [v0.2.3](https://github.com/tmg0/hero-motion/releases/tag/v0.2.3) and demo can be previewed in [Stackblitz](https://stackblitz.com/~/github.com/tmg0/hero-motion).

Thank you for raising this issue and for your contributions to `hero-motion`.
